version: "3.9"

services:
    ycgo-app:
        build: .
        image: ycgo-app:latest
        restart: always
        ports:
            - 6200:3000
        container_name: ycgo-app
    ycgo-uat-app:
        build: .
        image: ycgo-uat-app:latest
        restart: always
        ports:
            - 7200:3000
        container_name: ycgo-uat-app
