import { defineNuxtConfig } from 'nuxt/config'
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  app: {
      head: {
          htmlAttrs: {
              lang: "en",
          },
          charset: "utf-16",
          viewport: "width=device-width, initial-scale=1",
          title: "ASASA is a tour service in Laos and abroad",
          link: [{ rel: "icon", type: "image/png", href: "/logo_circle.png" }],
          script: [],
      },
  },
  compatibilityDate: "2025-10-10",
  devtools: { enabled: true },
  modules: [
    "@nuxt/eslint",
    "@nuxt/icon",
    "@nuxt/image",
    "@nuxt/scripts",
    "@nuxt/test-utils",
    "@nuxtjs/tailwindcss",
    [
      "@pinia/nuxt",
      {
        autoImports: ["defineStore", "acceptHMRUpdate", "storeToRefs"],
      },
    ],
    "@vee-validate/nuxt",
    "nuxt-swiper",
    "nuxt-tiptap-editor",
  ],
  runtimeConfig: {
    // The private keys which are only available server-side
    apiSecret: "123",
    API_URL: process.env.API_URL,
    API_KEY: process.env.API_KEY,
    CYT_SECRET: process.env.CYT_SECRET,
    // Keys within public are also exposed client-side
    public: {
      CDN: process.env.CDN || "",
      AGENT_URL: process.env.AGENT_URL || "",
      HOST_NAME: process.env.HOST_NAME || "",
      NODE_ENV: process.env.NODE_ENV,
    },
  },
  imports: {
    dirs: ["~/stores"],
  },
  css: ["~/assets/main.css", "vue-advanced-cropper/dist/style.css"],
  veeValidate: {
    autoImports: true,
    componentNames: {
      Form: "VeeForm",
      Field: "VeeField",
      FieldArray: "VeeFieldArray",
      ErrorMessage: "VeeErrorMessage",
    },
  },
  icon: {
     provider: 'iconify',
    // preload icons into your bundle
    // collections: [
    //   "ant-design",
    //   "bi",
    //   "bitcoin-icons",
    //   "bx",
    //   "carbon",
    //   "codex",
    //   "el",
    //   "eos-icons",
    //   "ep",
    //   "eva",
    //   "f7",
    //   "famicons",
    //   "file-icons",
    //   "flowbite",
    //   "fluent",
    //   "fluent-emoji-high-contrast",
    //   "fontisto",
    //   "game-icons",
    //   "gis",
    //   "gridicons",
    //   "heroicons",
    //   "hugeicons",
    //   "ic",
    //   "icon-park-outline",
    //   "icon-park-solid",
    //   "iconamoon",
    //   "iconoir",
    //   "ion",
    //   "la",
    //   "lets-icons",
    //   "line-md",
    //   "lsicon",
    //   "lucide",
    //   "majesticons",
    //   "map",
    //   "material-symbols",
    //   "material-symbols-light",
    //   "mdi",
    //   "mi",
    //   "mingcute",
    //   "nrk",
    //   "ph",
    //   "ri",
    //   "si",
    //   "simple-line-icons",
    //   "solar",
    //   "stash",
    //   "streamline-flex",
    //   "streamline-logos",
    //   "streamline-sharp",
    //   "streamline-sharp-color",
    //   "tabler",
    //   "uil",
    //   "uim",
    //   "uiw",
    //   "zondicons"
    // ],
  },
});
