export enum E_TOUR_TYPE {
    DOMESTIC = "DOMESTIC",
    INTERNATIONAL = "INTERNATIONAL ",
}

export enum E_TOUR_CATEGORY {
    SINGLE = "SINGLE",
    GROUP = "GROUP",
}

export enum E_TOUR_STATUS {
    PENDING = "PENDING",
    TRAVELING = "TRAVELING",
    COMPLETED = "COMPLETED",
    CANCELED = "CANCELED",
}

export enum E_PAYMENT_STATUS {
    PENDING = "PENDING",
    SUCCESS = "SUCCESS",
    FAILED = "FAILED",
}

export enum E_REGION {
    NORTHERN = "NORTHERN",
    CENTER = "CENTER",
    SOUTH = "SOUTH",
}
